# **EXP - 5**

**Singular Value Decomposition (SVD) Program**

In [11]:
#import libraries
import numpy as np
import pandas as pd

#step 1 : define a 3x3 matrix

A = np.array([[1,1],[7,7]])

#perform svd
U , S, Vt = np.linalg.svd(A)
#print the results
print("Original matrix:")
print(A)

print("\n Left Singlular Vectors (U):")
print(U)

print("\n Singular Values (S):")
print(S)

print("\n Right Singular Vector transposed (Vt):")
print(Vt)

#step 4: reconstruct the original matrix using U,S,Vt
#Note : svd returns s as a vector , we need to convert it into a diagonal matrix
Sigma = np.zeros((A.shape[0],A.shape[1]))
np.fill_diagonal(Sigma,S)

#reconstruct original matrix
A_reconstructed = np.dot(U,np.dot(Sigma,Vt))

#print the reconstructed matrix
print("\n Reconstructed Matrix:")
print(A_reconstructed)

Original matrix:
[[1 1]
 [7 7]]

 Left Singlular Vectors (U):
[[-0.14142136 -0.98994949]
 [-0.98994949  0.14142136]]

 Singular Values (S):
[10.  0.]

 Right Singular Vector transposed (Vt):
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

 Reconstructed Matrix:
[[1. 1.]
 [7. 7.]]
